server:
  port: 8083
  servlet:
    session:
      cookie:
        same-site: LAX
        secure: false
        http-only: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/tasko_db
    username: tasko
    password: tasko

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email

logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info